drone-hub:
  availability:
    minimal-battery: 25
    available-states:
      - IDLE
      - LOADED
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: move-me-to-env
    password: move-me-to-env
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
