drone-hub:
  availability:
    minimal-battery: 25
    available-states:
      - IDLE
      - LOADED
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
