# For now i leave build stage in docker file for easy launch,
# but in real word application it shouldn be there
FROM maven:3.8.7-eclipse-temurin-17-alpine as build

WORKDIR build
COPY ./src /build/src
COPY pom.xml /build/pom.xml
RUN mvn clean install

FROM openjdk:17-slim-buster as app

ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD

ENV DATABASE_USERNAME $DATABASE_USERNAME
ENV DATABASE_PASSWORD $DATABASE_PASSWORD

WORKDIR /app
COPY --from=build /build/target /app

CMD ["java", "-jar", "DroneHub-0.0.1-SNAPSHOT.jar"]